const actions = {
  SET_LIST: "SET_LIST",
  TOGGLE_ITEM: "TOGGLE_ITEM",
  ADD_ITEM: "ADD_ITEM",
  DELETE_COMPLETED_TODOS: "DELETE_COMPLETED_TODOS",
  SET_MODAL: "SET_MODAL",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  DELETE_PERSON: "DELETE_PERSON",
};

export default actions;
